database:
  authentication: none
  bucket: mine-ai-mnist
  endpoint: http://s3.us-east-1.amazonaws.com/
  type: s3
queue: local
resources_needed:
  cpus: 2
  gpus: 0
  hdd: 60g
  ram: 3g
saveMetricsFrequency: 1m
saveWorkspaceFrequency: 1m
server:
  authentication: none
storage:
  bucket: studio-ml-storage
  endpoint: http://s3.us-east-1.amazonaws.com/
  type: s3
verbose: true
